sudo: required

language: bash

services:
  - docker

before_install:
   - docker build -t madsequipo14/mads-todolist-2017:$TRAVIS_BUILD_NUMBER .

script:
   - docker run --rm madsequipo14/mads-todolist-2017:$TRAVIS_BUILD_NUMBER /bin/bash -c "sbt test"
   - docker run -d --rm -p 3306:3306 --name play-mysql -e MYSQL_ROOT_PASSWORD=mads -e MYSQL_DATABASE=mads mysql
   - docker run --link play-mysql:mysql --rm -e DB_URL="jdbc:mysql://play-mysql:3306/mads" -e DB_USER_NAME="root" -e DB_USER_PASSWD="mads" madsequipo14/mads-todolist-2017:$TRAVIS_BUILD_NUMBER /bin/bash -c "sbt '; set javaOptions += \"-Dconfig.file=conf/integration.conf\"; test'"
